// 품사 사전 확장판 — 자주 쓰는 단어 대량 추가
import type { PartOfSpeech } from '../constants/partOfSpeech';

type Entry = { pos: PartOfSpeech; ko?: string };

// =====================================================
// 스페인어 확장 — 약 250 단어
// =====================================================
export const ES_EXTRA: Record<string, Entry> = {
  // 의문사
  'qué': { pos: 'interjection', ko: '무엇' },
  'cuál': { pos: 'interjection', ko: '어느' },
  'quién': { pos: 'subject', ko: '누구' },
  'cuándo': { pos: 'adverb', ko: '언제' },
  'dónde': { pos: 'adverb', ko: '어디' },
  'cómo': { pos: 'adverb', ko: '어떻게' },
  'cuánto': { pos: 'adjective', ko: '얼마나' },

  // 시간
  'ayer': { pos: 'adverb', ko: '어제' },
  'hoy': { pos: 'adverb', ko: '오늘' },
  'mañana': { pos: 'adverb', ko: '내일/아침' },
  'noche': { pos: 'object', ko: '밤' },
  'tarde': { pos: 'object', ko: '오후' },
  'semana': { pos: 'object', ko: '주' },
  'mes': { pos: 'object', ko: '월' },
  'año': { pos: 'object', ko: '년' },
  'hora': { pos: 'object', ko: '시간' },
  'minuto': { pos: 'object', ko: '분' },
  'siempre': { pos: 'adverb', ko: '항상' },
  'nunca': { pos: 'adverb', ko: '절대 안' },
  'antes': { pos: 'adverb', ko: '이전' },
  'después': { pos: 'adverb', ko: '이후' },
  'pronto': { pos: 'adverb', ko: '곧' },
  'temprano': { pos: 'adverb', ko: '일찍' },

  // 자주 쓰는 동사 활용
  'sé': { pos: 'verb', ko: '안다' },
  'sabes': { pos: 'verb', ko: '안다(2)' },
  'sabe': { pos: 'verb', ko: '안다(3)' },
  'conoces': { pos: 'verb', ko: '알다(2)' },
  'conozco': { pos: 'verb', ko: '알다(1)' },
  'digo': { pos: 'verb', ko: '말하다(1)' },
  'dijo': { pos: 'verb', ko: '말했다' },
  'dice': { pos: 'verb', ko: '말한다' },
  'decir': { pos: 'verb', ko: '말하다' },
  'doy': { pos: 'verb', ko: '주다(1)' },
  'das': { pos: 'verb', ko: '주다(2)' },
  'dame': { pos: 'verb', ko: '나에게 줘' },
  'hablo': { pos: 'verb', ko: '말하다(1)' },
  'hablás': { pos: 'verb', ko: '말하다(vos)' },
  'habla': { pos: 'verb', ko: '말하다(3)' },
  'hablamos': { pos: 'verb', ko: '우리 말하다' },
  'comer': { pos: 'verb', ko: '먹다' },
  'como': { pos: 'verb', ko: '먹다/처럼' },
  'comiste': { pos: 'verb', ko: '먹었다(2)' },
  'vivir': { pos: 'verb', ko: '살다' },
  'vivo': { pos: 'verb', ko: '살다(1)' },
  'vive': { pos: 'verb', ko: '살다(3)' },
  'pensar': { pos: 'verb', ko: '생각하다' },
  'pienso': { pos: 'verb', ko: '생각한다(1)' },
  'piensas': { pos: 'verb', ko: '생각한다(2)' },
  'creer': { pos: 'verb', ko: '믿다' },
  'creo': { pos: 'verb', ko: '믿다(1)' },
  'crees': { pos: 'verb', ko: '믿다(2)' },
  'sentir': { pos: 'verb', ko: '느끼다' },
  'siento': { pos: 'verb', ko: '느낀다(1)' },
  'siente': { pos: 'verb', ko: '느낀다(3)' },
  'sentí': { pos: 'verb', ko: '느꼈다' },
  'venir': { pos: 'verb', ko: '오다' },
  'vengo': { pos: 'verb', ko: '오다(1)' },
  'viene': { pos: 'verb', ko: '오다(3)' },
  'vení': { pos: 'verb', ko: '와(vos)' },
  'salir': { pos: 'verb', ko: '나가다' },
  'salgo': { pos: 'verb', ko: '나간다(1)' },
  'salí': { pos: 'verb', ko: '나갔다' },
  'volver': { pos: 'verb', ko: '돌아오다' },
  'vuelvo': { pos: 'verb', ko: '돌아온다(1)' },
  'volvió': { pos: 'verb', ko: '돌아왔다' },
  'empezar': { pos: 'verb', ko: '시작하다' },
  'empecé': { pos: 'verb', ko: '시작했다(1)' },
  'empezó': { pos: 'verb', ko: '시작했다(3)' },
  'terminar': { pos: 'verb', ko: '끝내다' },
  'terminé': { pos: 'verb', ko: '끝냈다(1)' },
  'aprender': { pos: 'verb', ko: '배우다' },
  'aprendo': { pos: 'verb', ko: '배운다(1)' },
  'aprendí': { pos: 'verb', ko: '배웠다(1)' },
  'enseñar': { pos: 'verb', ko: '가르치다' },
  'recordar': { pos: 'verb', ko: '기억하다' },
  'me acuerdo': { pos: 'verb', ko: '기억난다' },
  'olvidar': { pos: 'verb', ko: '잊다' },
  'olvidé': { pos: 'verb', ko: '잊었다' },
  'tener': { pos: 'verb', ko: '가지다' },
  'tenés': { pos: 'verb', ko: '가지다(vos)' },
  'tuve': { pos: 'verb', ko: '가졌다' },
  'haber': { pos: 'verb', ko: '있다(완료)' },
  'había': { pos: 'verb', ko: '있었다' },
  'hubo': { pos: 'verb', ko: '있었다(완료)' },
  'estar': { pos: 'verb', ko: '있다/이다' },

  // 형용사
  'bueno': { pos: 'adjective', ko: '좋은(남)' },
  'buena': { pos: 'adjective', ko: '좋은(여)' },
  'malo': { pos: 'adjective', ko: '나쁜(남)' },
  'mala': { pos: 'adjective', ko: '나쁜(여)' },
  'grande': { pos: 'adjective', ko: '큰' },
  'pequeño': { pos: 'adjective', ko: '작은' },
  'pequeña': { pos: 'adjective', ko: '작은(여)' },
  'joven': { pos: 'adjective', ko: '젊은' },
  'viejo': { pos: 'adjective', ko: '늙은' },
  'vieja': { pos: 'adjective', ko: '늙은(여)' },
  'lindo': { pos: 'adjective', ko: '예쁜' },
  'linda': { pos: 'adjective', ko: '예쁜(여)' },
  'feo': { pos: 'adjective', ko: '못생긴' },
  'alto': { pos: 'adjective', ko: '높은' },
  'bajo': { pos: 'adjective', ko: '낮은' },
  'rápido': { pos: 'adjective', ko: '빠른' },
  'lento': { pos: 'adjective', ko: '느린' },
  'fácil': { pos: 'adjective', ko: '쉬운' },
  'difícil': { pos: 'adjective', ko: '어려운' },
  'caro': { pos: 'adjective', ko: '비싼' },
  'barato': { pos: 'adjective', ko: '싼' },
  'feliz': { pos: 'adjective', ko: '행복한' },
  'triste': { pos: 'adjective', ko: '슬픈' },
  'enojado': { pos: 'adjective', ko: '화난' },
  'tranquilo': { pos: 'adjective', ko: '편안한' },
  'mejor': { pos: 'adjective', ko: '더 좋은' },
  'peor': { pos: 'adjective', ko: '더 나쁜' },
  'increíble': { pos: 'adjective', ko: '놀라운' },
  'maravilloso': { pos: 'adjective', ko: '경이로운' },
  'perfecto': { pos: 'adjective', ko: '완벽한' },
  'preciosa': { pos: 'adjective', ko: '귀한(여)' },

  // 부사 추가
  'así': { pos: 'adverb', ko: '이렇게' },
  'entonces': { pos: 'adverb', ko: '그럼' },
  'igual': { pos: 'adverb', ko: '똑같이' },
  'casi': { pos: 'adverb', ko: '거의' },
  'apenas': { pos: 'adverb', ko: '간신히' },
  'demasiado': { pos: 'adverb', ko: '너무 많이' },
  'bastante': { pos: 'adverb', ko: '충분히' },
  'realmente': { pos: 'adverb', ko: '정말로' },
  'verdaderamente': { pos: 'adverb', ko: '진정으로' },
  'tal vez': { pos: 'adverb', ko: '아마도' },
  'quizás': { pos: 'adverb', ko: '아마' },

  // 가족
  'familia': { pos: 'object', ko: '가족' },
  'madre': { pos: 'object', ko: '어머니' },
  'mamá': { pos: 'object', ko: '엄마' },
  'padre': { pos: 'object', ko: '아버지' },
  'papá': { pos: 'object', ko: '아빠' },
  'hermano': { pos: 'object', ko: '오빠/형/남동생' },
  'hermana': { pos: 'object', ko: '언니/누나/여동생' },
  'hijo': { pos: 'object', ko: '아들' },
  'hija': { pos: 'object', ko: '딸' },
  'abuelo': { pos: 'object', ko: '할아버지' },
  'abuela': { pos: 'object', ko: '할머니' },
  'tío': { pos: 'object', ko: '삼촌' },
  'tía': { pos: 'object', ko: '이모/고모' },
  'primo': { pos: 'object', ko: '사촌(남)' },
  'prima': { pos: 'object', ko: '사촌(여)' },
  'amigo': { pos: 'object', ko: '친구(남)' },
  'amiga': { pos: 'object', ko: '친구(여)' },
  'pareja': { pos: 'object', ko: '커플/배우자' },
  'esposa': { pos: 'object', ko: '아내' },
  'esposo': { pos: 'object', ko: '남편' },
  'novia': { pos: 'object', ko: '여자친구' },
  'novio': { pos: 'object', ko: '남자친구' },

  // 신체
  'cabeza': { pos: 'object', ko: '머리' },
  'cara': { pos: 'object', ko: '얼굴' },
  'mano': { pos: 'object', ko: '손' },
  'manos': { pos: 'object', ko: '손들' },
  'pie': { pos: 'object', ko: '발' },
  'pies': { pos: 'object', ko: '발들' },
  'ojo': { pos: 'object', ko: '눈' },
  'ojos': { pos: 'object', ko: '눈들' },
  'brazo': { pos: 'object', ko: '팔' },
  'brazos': { pos: 'object', ko: '팔들' },
  'pierna': { pos: 'object', ko: '다리' },
  'piernas': { pos: 'object', ko: '다리들' },
  'corazón': { pos: 'object', ko: '심장' },
  'cuerpo': { pos: 'object', ko: '몸' },
  'espalda': { pos: 'object', ko: '등' },
  'rodilla': { pos: 'object', ko: '무릎' },
  'cintura': { pos: 'object', ko: '허리' },
  'cuello': { pos: 'object', ko: '목' },
  'hombros': { pos: 'object', ko: '어깨' },

  // 음식·음료
  'comida': { pos: 'object', ko: '음식' },
  'agua': { pos: 'object', ko: '물' },
  'café': { pos: 'object', ko: '커피' },
  'té': { pos: 'object', ko: '차' },
  'vino': { pos: 'object', ko: '와인' },
  'cerveza': { pos: 'object', ko: '맥주' },
  'leche': { pos: 'object', ko: '우유' },
  'pan': { pos: 'object', ko: '빵' },
  'carne': { pos: 'object', ko: '고기' },
  'pescado': { pos: 'object', ko: '생선' },
  'fruta': { pos: 'object', ko: '과일' },
  'ensalada': { pos: 'object', ko: '샐러드' },
  'azúcar': { pos: 'object', ko: '설탕' },
  'sal': { pos: 'object', ko: '소금' },
  'mate': { pos: 'object', ko: '마테차' },
  'asado': { pos: 'object', ko: '아사도(BBQ)' },
  'empanada': { pos: 'object', ko: '엠파나다' },

  // 색깔
  'rojo': { pos: 'adjective', ko: '빨간' },
  'roja': { pos: 'adjective', ko: '빨간(여)' },
  'azul': { pos: 'adjective', ko: '파란' },
  'verde': { pos: 'adjective', ko: '초록' },
  'amarillo': { pos: 'adjective', ko: '노란' },
  'blanco': { pos: 'adjective', ko: '흰' },
  'blanca': { pos: 'adjective', ko: '흰(여)' },
  'negro': { pos: 'adjective', ko: '검은' },
  'negra': { pos: 'adjective', ko: '검은(여)' },

  // 수사
  'cero': { pos: 'adjective', ko: '0' },
  'uno': { pos: 'adjective', ko: '1' },
  'dos': { pos: 'adjective', ko: '2' },
  'tres': { pos: 'adjective', ko: '3' },
  'cuatro': { pos: 'adjective', ko: '4' },
  'cinco': { pos: 'adjective', ko: '5' },
  'seis': { pos: 'adjective', ko: '6' },
  'siete': { pos: 'adjective', ko: '7' },
  'ocho': { pos: 'adjective', ko: '8' },
  'nueve': { pos: 'adjective', ko: '9' },
  'diez': { pos: 'adjective', ko: '10' },
  'cien': { pos: 'adjective', ko: '100' },
  'mil': { pos: 'adjective', ko: '1,000' },

  // 일상
  'casa': { pos: 'object', ko: '집' },
  'trabajo': { pos: 'object', ko: '일' },
  'oficina': { pos: 'object', ko: '사무실' },
  'escuela': { pos: 'object', ko: '학교' },
  'libro': { pos: 'object', ko: '책' },
  'música': { pos: 'object', ko: '음악' },
  'película': { pos: 'object', ko: '영화' },
  'auto': { pos: 'object', ko: '차' },
  'subte': { pos: 'object', ko: '지하철' },
  'colectivo': { pos: 'object', ko: '버스' },
  'bici': { pos: 'object', ko: '자전거' },
  'celular': { pos: 'object', ko: '휴대폰' },
  'dinero': { pos: 'object', ko: '돈' },
  'plata': { pos: 'object', ko: '돈(구어)' },
  'tiempo': { pos: 'object', ko: '시간' },
  'momento': { pos: 'object', ko: '순간' },
  'lugar': { pos: 'object', ko: '장소' },
  'persona': { pos: 'object', ko: '사람' },
  'gente': { pos: 'object', ko: '사람들' },
  'mundo': { pos: 'object', ko: '세상' },
  'país': { pos: 'object', ko: '나라' },
  'ciudad': { pos: 'object', ko: '도시' },

  // 탱고 추가 용어
  'orquesta': { pos: 'object', ko: '오케스트라' },
  'cortina': { pos: 'object', ko: '코르티나' },
  'cabeceo': { pos: 'object', ko: '카베세오' },
  'vals': { pos: 'object', ko: '발스' },
  'salida': { pos: 'object', ko: '시작/사리다' },
  'caminata': { pos: 'object', ko: '걷기' },
  'gancho': { pos: 'object', ko: '간초' },
  'bailarín': { pos: 'object', ko: '댄서(남)' },
  'bailarina': { pos: 'object', ko: '댄서(여)' },
  'pareja': { pos: 'object', ko: '파트너' },
  'profesor': { pos: 'object', ko: '선생님(남)' },
  'profesora': { pos: 'object', ko: '선생님(여)' },
  'alumno': { pos: 'object', ko: '학생(남)' },
  'alumna': { pos: 'object', ko: '학생(여)' },
};

// =====================================================
// 영어 확장 — 약 200 단어
// =====================================================
export const EN_EXTRA: Record<string, Entry> = {
  // 의문사
  'what': { pos: 'interjection', ko: '무엇' },
  'who': { pos: 'subject', ko: '누구' },
  'which': { pos: 'adjective', ko: '어느' },
  'when': { pos: 'adverb', ko: '언제' },
  'where': { pos: 'adverb', ko: '어디' },
  'why': { pos: 'adverb', ko: '왜' },
  'how': { pos: 'adverb', ko: '어떻게' },

  // 시간
  'yesterday': { pos: 'adverb', ko: '어제' },
  'today': { pos: 'adverb', ko: '오늘' },
  'tomorrow': { pos: 'adverb', ko: '내일' },
  'tonight': { pos: 'adverb', ko: '오늘밤' },
  'morning': { pos: 'object', ko: '아침' },
  'night': { pos: 'object', ko: '밤' },
  'evening': { pos: 'object', ko: '저녁' },
  'week': { pos: 'object', ko: '주' },
  'month': { pos: 'object', ko: '월' },
  'year': { pos: 'object', ko: '년' },
  'hour': { pos: 'object', ko: '시간' },
  'minute': { pos: 'object', ko: '분' },
  'always': { pos: 'adverb', ko: '항상' },
  'never': { pos: 'adverb', ko: '절대 안' },
  'sometimes': { pos: 'adverb', ko: '가끔' },
  'often': { pos: 'adverb', ko: '자주' },

  // 동사
  'know': { pos: 'verb', ko: '알다' },
  'knew': { pos: 'verb', ko: '알았다' },
  'known': { pos: 'verb', ko: '알려진' },
  'say': { pos: 'verb', ko: '말하다' },
  'said': { pos: 'verb', ko: '말했다' },
  'tell': { pos: 'verb', ko: '말하다' },
  'told': { pos: 'verb', ko: '말했다' },
  'speak': { pos: 'verb', ko: '말하다' },
  'spoke': { pos: 'verb', ko: '말했다' },
  'talk': { pos: 'verb', ko: '얘기하다' },
  'eat': { pos: 'verb', ko: '먹다' },
  'ate': { pos: 'verb', ko: '먹었다' },
  'drink': { pos: 'verb', ko: '마시다' },
  'drank': { pos: 'verb', ko: '마셨다' },
  'live': { pos: 'verb', ko: '살다' },
  'lived': { pos: 'verb', ko: '살았다' },
  'work': { pos: 'verb', ko: '일하다' },
  'worked': { pos: 'verb', ko: '일했다' },
  'study': { pos: 'verb', ko: '공부하다' },
  'studied': { pos: 'verb', ko: '공부했다' },
  'play': { pos: 'verb', ko: '놀다/연주하다' },
  'played': { pos: 'verb', ko: '놀았다' },
  'walk': { pos: 'verb', ko: '걷다' },
  'walked': { pos: 'verb', ko: '걸었다' },
  'run': { pos: 'verb', ko: '뛰다' },
  'ran': { pos: 'verb', ko: '뛰었다' },
  'sit': { pos: 'verb', ko: '앉다' },
  'sat': { pos: 'verb', ko: '앉았다' },
  'stand': { pos: 'verb', ko: '서다' },
  'stood': { pos: 'verb', ko: '섰다' },
  'sleep': { pos: 'verb', ko: '자다' },
  'slept': { pos: 'verb', ko: '잤다' },
  'wake': { pos: 'verb', ko: '깨다' },
  'woke': { pos: 'verb', ko: '깼다' },
  'love': { pos: 'verb', ko: '사랑하다' },
  'loved': { pos: 'verb', ko: '사랑했다' },
  'want': { pos: 'verb', ko: '원하다' },
  'wanted': { pos: 'verb', ko: '원했다' },
  'need': { pos: 'verb', ko: '필요하다' },
  'needed': { pos: 'verb', ko: '필요했다' },
  'try': { pos: 'verb', ko: '시도하다' },
  'tried': { pos: 'verb', ko: '시도했다' },
  'find': { pos: 'verb', ko: '찾다' },
  'found': { pos: 'verb', ko: '찾았다' },
  'give': { pos: 'verb', ko: '주다' },
  'gave': { pos: 'verb', ko: '주었다' },
  'take': { pos: 'verb', ko: '가지다' },
  'took': { pos: 'verb', ko: '가졌다' },
  'meet': { pos: 'verb', ko: '만나다' },
  'met': { pos: 'verb', ko: '만났다' },
  'remember': { pos: 'verb', ko: '기억하다' },
  'forget': { pos: 'verb', ko: '잊다' },
  'forgot': { pos: 'verb', ko: '잊었다' },
  'understand': { pos: 'verb', ko: '이해하다' },
  'understood': { pos: 'verb', ko: '이해했다' },
  'become': { pos: 'verb', ko: '되다' },
  'became': { pos: 'verb', ko: '됐다' },
  'begin': { pos: 'verb', ko: '시작하다' },
  'began': { pos: 'verb', ko: '시작했다' },
  'start': { pos: 'verb', ko: '시작하다' },
  'started': { pos: 'verb', ko: '시작했다' },
  'finish': { pos: 'verb', ko: '끝내다' },
  'finished': { pos: 'verb', ko: '끝냈다' },
  'continue': { pos: 'verb', ko: '계속하다' },
  'change': { pos: 'verb', ko: '바꾸다' },
  'changed': { pos: 'verb', ko: '바꿨다' },

  // 형용사
  'big': { pos: 'adjective', ko: '큰' },
  'small': { pos: 'adjective', ko: '작은' },
  'long': { pos: 'adjective', ko: '긴' },
  'short': { pos: 'adjective', ko: '짧은' },
  'young': { pos: 'adjective', ko: '젊은' },
  'old': { pos: 'adjective', ko: '늙은' },
  'high': { pos: 'adjective', ko: '높은' },
  'low': { pos: 'adjective', ko: '낮은' },
  'fast': { pos: 'adjective', ko: '빠른' },
  'slow': { pos: 'adjective', ko: '느린' },
  'easy': { pos: 'adjective', ko: '쉬운' },
  'hard': { pos: 'adjective', ko: '어려운' },
  'happy': { pos: 'adjective', ko: '행복한' },
  'sad': { pos: 'adjective', ko: '슬픈' },
  'angry': { pos: 'adjective', ko: '화난' },
  'calm': { pos: 'adjective', ko: '편안한' },
  'better': { pos: 'adjective', ko: '더 좋은' },
  'worse': { pos: 'adjective', ko: '더 나쁜' },
  'best': { pos: 'adjective', ko: '최고' },
  'worst': { pos: 'adjective', ko: '최악' },
  'amazing': { pos: 'adjective', ko: '놀라운' },
  'wonderful': { pos: 'adjective', ko: '경이로운' },
  'perfect': { pos: 'adjective', ko: '완벽한' },
  'lovely': { pos: 'adjective', ko: '사랑스러운' },

  // 부사 추가
  'just': { pos: 'adverb', ko: '방금' },
  'almost': { pos: 'adverb', ko: '거의' },
  'enough': { pos: 'adverb', ko: '충분히' },
  'maybe': { pos: 'adverb', ko: '아마' },
  'perhaps': { pos: 'adverb', ko: '아마도' },
  'so': { pos: 'adverb', ko: '그래서/매우' },
  'quite': { pos: 'adverb', ko: '꽤' },

  // 가족
  'family': { pos: 'object', ko: '가족' },
  'mother': { pos: 'object', ko: '어머니' },
  'mom': { pos: 'object', ko: '엄마' },
  'father': { pos: 'object', ko: '아버지' },
  'dad': { pos: 'object', ko: '아빠' },
  'brother': { pos: 'object', ko: '형/오빠/남동생' },
  'sister': { pos: 'object', ko: '언니/누나/여동생' },
  'son': { pos: 'object', ko: '아들' },
  'daughter': { pos: 'object', ko: '딸' },
  'wife': { pos: 'object', ko: '아내' },
  'husband': { pos: 'object', ko: '남편' },
  'friend': { pos: 'object', ko: '친구' },
  'partner': { pos: 'object', ko: '파트너' },

  // 신체
  'head': { pos: 'object', ko: '머리' },
  'face': { pos: 'object', ko: '얼굴' },
  'hand': { pos: 'object', ko: '손' },
  'foot': { pos: 'object', ko: '발' },
  'feet': { pos: 'object', ko: '발들' },
  'eye': { pos: 'object', ko: '눈' },
  'eyes': { pos: 'object', ko: '눈들' },
  'arm': { pos: 'object', ko: '팔' },
  'leg': { pos: 'object', ko: '다리' },
  'heart': { pos: 'object', ko: '심장' },
  'body': { pos: 'object', ko: '몸' },
  'back': { pos: 'object', ko: '등' },
  'knee': { pos: 'object', ko: '무릎' },
  'shoulder': { pos: 'object', ko: '어깨' },

  // 일상
  'home': { pos: 'object', ko: '집' },
  'house': { pos: 'object', ko: '집' },
  'room': { pos: 'object', ko: '방' },
  'school': { pos: 'object', ko: '학교' },
  'office': { pos: 'object', ko: '사무실' },
  'job': { pos: 'object', ko: '일' },
  'book': { pos: 'object', ko: '책' },
  'movie': { pos: 'object', ko: '영화' },
  'music': { pos: 'object', ko: '음악' },
  'song': { pos: 'object', ko: '노래' },
  'phone': { pos: 'object', ko: '전화' },
  'car': { pos: 'object', ko: '차' },
  'bus': { pos: 'object', ko: '버스' },
  'subway': { pos: 'object', ko: '지하철' },
  'money': { pos: 'object', ko: '돈' },
  'time': { pos: 'object', ko: '시간' },
  'place': { pos: 'object', ko: '장소' },
  'people': { pos: 'object', ko: '사람들' },
  'world': { pos: 'object', ko: '세상' },
  'country': { pos: 'object', ko: '나라' },
  'city': { pos: 'object', ko: '도시' },

  // 음식
  'food': { pos: 'object', ko: '음식' },
  'water': { pos: 'object', ko: '물' },
  'coffee': { pos: 'object', ko: '커피' },
  'tea': { pos: 'object', ko: '차' },
  'wine': { pos: 'object', ko: '와인' },
  'beer': { pos: 'object', ko: '맥주' },
  'milk': { pos: 'object', ko: '우유' },
  'bread': { pos: 'object', ko: '빵' },
  'meat': { pos: 'object', ko: '고기' },
  'rice': { pos: 'object', ko: '쌀/밥' },

  // 수사
  'one': { pos: 'adjective', ko: '1' },
  'two': { pos: 'adjective', ko: '2' },
  'three': { pos: 'adjective', ko: '3' },
  'four': { pos: 'adjective', ko: '4' },
  'five': { pos: 'adjective', ko: '5' },
  'six': { pos: 'adjective', ko: '6' },
  'seven': { pos: 'adjective', ko: '7' },
  'eight': { pos: 'adjective', ko: '8' },
  'nine': { pos: 'adjective', ko: '9' },
  'ten': { pos: 'adjective', ko: '10' },
  'hundred': { pos: 'adjective', ko: '100' },
  'thousand': { pos: 'adjective', ko: '1,000' },
};

// =====================================================
// 중국어 확장 (greedy 매칭) — 약 100 단어
// =====================================================
export const ZH_EXTRA: { w: string; pos: PartOfSpeech; ko?: string }[] = [
  // 의문사
  { w: '什么', pos: 'interjection', ko: '무엇' },
  { w: '怎么样', pos: 'adverb', ko: '어때' },
  { w: '为什么', pos: 'adverb', ko: '왜' },
  { w: '哪里', pos: 'adverb', ko: '어디' },
  { w: '哪个', pos: 'adjective', ko: '어느' },
  { w: '怎么', pos: 'adverb', ko: '어떻게' },
  { w: '多少', pos: 'adjective', ko: '얼마' },
  { w: '几', pos: 'adjective', ko: '몇' },

  // 시간
  { w: '昨天', pos: 'adverb', ko: '어제' },
  { w: '今天', pos: 'adverb', ko: '오늘' },
  { w: '明天', pos: 'adverb', ko: '내일' },
  { w: '现在', pos: 'adverb', ko: '지금' },
  { w: '以前', pos: 'adverb', ko: '이전' },
  { w: '以后', pos: 'adverb', ko: '이후' },
  { w: '早上', pos: 'object', ko: '아침' },
  { w: '晚上', pos: 'object', ko: '저녁' },
  { w: '中午', pos: 'object', ko: '점심' },
  { w: '小时', pos: 'object', ko: '시간' },
  { w: '分钟', pos: 'object', ko: '분' },
  { w: '一会儿', pos: 'adverb', ko: '잠시 후' },
  { w: '马上', pos: 'adverb', ko: '곧' },

  // 양사
  { w: '个', pos: 'particle', ko: '개(양사)' },
  { w: '本', pos: 'particle', ko: '권' },
  { w: '张', pos: 'particle', ko: '장' },
  { w: '杯', pos: 'particle', ko: '잔' },
  { w: '双', pos: 'particle', ko: '쌍' },
  { w: '件', pos: 'particle', ko: '벌(옷)' },
  { w: '辆', pos: 'particle', ko: '대(차)' },
  { w: '只', pos: 'particle', ko: '마리' },
  { w: '块', pos: 'particle', ko: '조각/위안' },
  { w: '位', pos: 'particle', ko: '분(존칭)' },
  { w: '门', pos: 'particle', ko: '문/과목 양사' },

  // 동사
  { w: '说话', pos: 'verb', ko: '말하다' },
  { w: '说', pos: 'verb', ko: '말하다' },
  { w: '告诉', pos: 'verb', ko: '알리다' },
  { w: '知道', pos: 'verb', ko: '알다' },
  { w: '认识', pos: 'verb', ko: '알다(만난적)' },
  { w: '吃', pos: 'verb', ko: '먹다' },
  { w: '喝', pos: 'verb', ko: '마시다' },
  { w: '住', pos: 'verb', ko: '살다' },
  { w: '工作', pos: 'verb', ko: '일하다' },
  { w: '学习', pos: 'verb', ko: '공부하다' },
  { w: '玩', pos: 'verb', ko: '놀다' },
  { w: '走', pos: 'verb', ko: '걷다' },
  { w: '跑', pos: 'verb', ko: '뛰다' },
  { w: '坐', pos: 'verb', ko: '앉다' },
  { w: '站', pos: 'verb', ko: '서다' },
  { w: '睡觉', pos: 'verb', ko: '자다' },
  { w: '起来', pos: 'verb', ko: '일어나다' },
  { w: '爱', pos: 'verb', ko: '사랑하다' },
  { w: '需要', pos: 'verb', ko: '필요하다' },
  { w: '试试', pos: 'verb', ko: '시도하다' },
  { w: '找', pos: 'verb', ko: '찾다' },
  { w: '给', pos: 'verb', ko: '주다' },
  { w: '拿', pos: 'verb', ko: '가지다' },
  { w: '见面', pos: 'verb', ko: '만나다' },
  { w: '记得', pos: 'verb', ko: '기억하다' },
  { w: '忘', pos: 'verb', ko: '잊다' },
  { w: '懂', pos: 'verb', ko: '이해하다' },
  { w: '开始', pos: 'verb', ko: '시작하다' },
  { w: '结束', pos: 'verb', ko: '끝내다' },
  { w: '继续', pos: 'verb', ko: '계속하다' },
  { w: '改变', pos: 'verb', ko: '바꾸다' },

  // 형용사
  { w: '大', pos: 'adjective', ko: '큰' },
  { w: '小', pos: 'adjective', ko: '작은' },
  { w: '长', pos: 'adjective', ko: '긴' },
  { w: '短', pos: 'adjective', ko: '짧은' },
  { w: '高', pos: 'adjective', ko: '높은' },
  { w: '矮', pos: 'adjective', ko: '낮은' },
  { w: '快', pos: 'adjective', ko: '빠른' },
  { w: '慢', pos: 'adjective', ko: '느린' },
  { w: '容易', pos: 'adjective', ko: '쉬운' },
  { w: '难', pos: 'adjective', ko: '어려운' },
  { w: '贵', pos: 'adjective', ko: '비싼' },
  { w: '便宜', pos: 'adjective', ko: '싼' },
  { w: '开心', pos: 'adjective', ko: '행복한' },
  { w: '伤心', pos: 'adjective', ko: '슬픈' },
  { w: '生气', pos: 'adjective', ko: '화난' },
  { w: '安静', pos: 'adjective', ko: '조용한' },
  { w: '热闹', pos: 'adjective', ko: '시끄러운' },

  // 가족
  { w: '家人', pos: 'object', ko: '가족' },
  { w: '妈妈', pos: 'object', ko: '엄마' },
  { w: '爸爸', pos: 'object', ko: '아빠' },
  { w: '哥哥', pos: 'object', ko: '오빠/형' },
  { w: '姐姐', pos: 'object', ko: '언니/누나' },
  { w: '弟弟', pos: 'object', ko: '남동생' },
  { w: '妹妹', pos: 'object', ko: '여동생' },
  { w: '儿子', pos: 'object', ko: '아들' },
  { w: '女儿', pos: 'object', ko: '딸' },
  { w: '朋友', pos: 'object', ko: '친구' },

  // 신체
  { w: '头', pos: 'object', ko: '머리' },
  { w: '脸', pos: 'object', ko: '얼굴' },
  { w: '手', pos: 'object', ko: '손' },
  { w: '脚', pos: 'object', ko: '발' },
  { w: '眼睛', pos: 'object', ko: '눈' },
  { w: '心', pos: 'object', ko: '마음' },
  { w: '身体', pos: 'object', ko: '몸' },

  // 일상
  { w: '家', pos: 'object', ko: '집' },
  { w: '学校', pos: 'object', ko: '학교' },
  { w: '公司', pos: 'object', ko: '회사' },
  { w: '书', pos: 'object', ko: '책' },
  { w: '电影', pos: 'object', ko: '영화' },
  { w: '电话', pos: 'object', ko: '전화' },
  { w: '汽车', pos: 'object', ko: '자동차' },
  { w: '钱', pos: 'object', ko: '돈' },
  { w: '时间', pos: 'object', ko: '시간' },
  { w: '地方', pos: 'object', ko: '장소' },
  { w: '人', pos: 'object', ko: '사람' },
  { w: '世界', pos: 'object', ko: '세상' },
  { w: '国家', pos: 'object', ko: '나라' },
  { w: '城市', pos: 'object', ko: '도시' },

  // 음식
  { w: '食物', pos: 'object', ko: '음식' },
  { w: '水', pos: 'object', ko: '물' },
  { w: '咖啡', pos: 'object', ko: '커피' },
  { w: '茶', pos: 'object', ko: '차' },
  { w: '红酒', pos: 'object', ko: '와인' },
  { w: '啤酒', pos: 'object', ko: '맥주' },
  { w: '牛奶', pos: 'object', ko: '우유' },
  { w: '面包', pos: 'object', ko: '빵' },
  { w: '肉', pos: 'object', ko: '고기' },
  { w: '米饭', pos: 'object', ko: '쌀밥' },

  // 수사
  { w: '零', pos: 'adjective', ko: '0' },
  { w: '十', pos: 'adjective', ko: '10' },
  { w: '百', pos: 'adjective', ko: '100' },
  { w: '千', pos: 'adjective', ko: '1,000' },
  { w: '万', pos: 'adjective', ko: '10,000' },
];
